export const countryList = [
    { id: "0", value: "Choose Country" },
    { id: "1", value: "Afghanistan" },
    { id: "2", value: "Albania" },
    { id: "3", value: "Algeria" },
    { id: "4", value: "Andorra" },
    { id: "5", value: "Angola" },
    { id: "6", value: "Antigua and Barbuda" },
    { id: "7", value: "Argentina" },
    { id: "8", value: "Armenia" },
    { id: "9", value: "Australia" },
    { id: "10", value: "Austria" },
    { id: "11", value: "Azerbaijan" },
    { id: "12", value: "Bahamas" },
    { id: "13", value: "Bahrain" },
    { id: "14", value: "Bangladesh" },
    { id: "15", value: "Barbados" },
    { id: "16", value: "Belarus" },
    { id: "17", value: "Belgium" },
    { id: "18", value: "Belize" },
    { id: "19", value: "Benin" },
    { id: "20", value: "Bhutan" },
    { id: "21", value: "Bolivia" },
    { id: "22", value: "Bosnia and Herzegovina" },
    { id: "23", value: "Botswana" },
    { id: "24", value: "Brazil" },
    { id: "25", value: "Brunei" },
    { id: "26", value: "Bulgaria" },
    { id: "27", value: "Burkina Faso" },
    { id: "28", value: "Burundi" },
    { id: "29", value: "Cabo Verde" },
    { id: "30", value: "Cambodia" },
    { id: "31", value: "Cameroon" },
    { id: "32", value: "Canada" },
    { id: "33", value: "Central African Republic" },
    { id: "34", value: "Chad" },
    { id: "35", value: "Chile" },
    { id: "36", value: "China" },
    { id: "37", value: "Colombia" },
    { id: "38", value: "Comoros" },
    { id: "39", value: "Congo, Democratic Republic of the" },
    { id: "40", value: "Congo, Republic of the" },
    { id: "41", value: "Costa Rica" },
    { id: "42", value: "Cote d'Ivoire" },
    { id: "43", value: "Croatia" },
    { id: "44", value: "Cuba" },
    { id: "45", value: "Cyprus" },
    { id: "46", value: "Czech Republic" },
    { id: "47", value: "Denmark" },
    { id: "48", value: "Djibouti" },
    { id: "49", value: "Dominica" },
    { id: "50", value: "Dominican Republic" },
    { id: "51", value: "East Timor (Timor-Leste)" },
    { id: "52", value: "Ecuador" },
    { id: "53", value: "Egypt" },
    { id: "54", value: "El Salvador" },
    { id: "55", value: "Equatorial Guinea" },
    { id: "56", value: "Eritrea" },
    { id: "57", value: "Estonia" },
    { id: "58", value: "Eswatini" },
    { id: "59", value: "Ethiopia" },
    { id: "60", value: "Fiji" },
    { id: "61", value: "Finland" },
    { id: "62", value: "France" },
    { id: "63", value: "Gabon" },
    { id: "64", value: "Gambia" },
    { id: "65", value: "Georgia" },
    { id: "66", value: "Germany" },
    { id: "67", value: "Ghana" },
    { id: "68", value: "Greece" },
    { id: "69", value: "Grenada" },
    { id: "70", value: "Guatemala" },
    { id: "71", value: "Guinea" },
    { id: "72", value: "Guinea-Bissau" },
    { id: "73", value: "Guyana" },
    { id: "74", value: "Haiti" },
    { id: "75", value: "Honduras" },
    { id: "76", value: "Hungary" },
    { id: "77", value: "Iceland" },
    { id: "78", value: "India" },
    { id: "79", value: "Indonesia" },
    { id: "80", value: "Iran" },
    { id: "81", value: "Iraq" },
    { id: "82", value: "Ireland" },
    { id: "83", value: "Israel" },
    { id: "84", value: "Italy" },
    { id: "85", value: "Jamaica" },
    { id: "86", value: "Japan" },
    { id: "87", value: "Jordan" },
    { id: "88", value: "Kazakhstan" },
    { id: "89", value: "Kenya" },
    { id: "90", value: "Kiribati" },
    { id: "91", value: "Korea, North" },
    { id: "92", value: "Korea, South" },
    { id: "93", value: "Kosovo" },
    { id: "94", value: "Kuwait" },
    { id: "95", value: "Kyrgyzstan" },
    { id: "96", value: "Laos" },
    { id: "97", value: "Latvia" },
    { id: "98", value: "Lebanon" },
    { id: "99", value: "Lesotho" },
    { id: "100", value: "Liberia" },
    { id: "101", value: "Libya" },
    { id: "102", value: "Liechtenstein" },
    { id: "103", value: "Lithuania" },
    { id: "104", value: "Luxembourg" },
    { id: "105", value: "Madagascar" },
    { id: "106", value: "Malawi" },
    { id: "107", value: "Malaysia" },
    { id: "108", value: "Maldives" },
    { id: "109", value: "Mali" },
    { id: "110", value: "Malta" },
    { id: "111", value: "Marshall Islands" },
    { id: "112", value: "Mauritania" },
    { id: "113", value: "Mauritius" },
    { id: "114", value: "Mexico" },
    { id: "115", value: "Micronesia" },
    { id: "116", value: "Moldova" },
    { id: "117", value: "Monaco" },
    { id: "118", value: "Mongolia" },
    { id: "119", value: "Montenegro" },
    { id: "120", value: "Morocco" },
    { id: "121", value: "Mozambique" },
    { id: "122", value: "Myanmar (Burma)" },
    { id: "123", value: "Namibia" },
    { id: "124", value: "Nauru" },
    { id: "125", value: "Nepal" },
    { id: "126", value: "Netherlands" },
    { id: "127", value: "New Zealand" },
    { id: "128", value: "Nicaragua" },
    { id: "129", value: "Niger" },
    { id: "130", value: "Nigeria" },
    { id: "131", value: "North Macedonia (Macedonia)" },
    { id: "132", value: "Norway" },
    { id: "133", value: "Oman" },
    { id: "134", value: "Pakistan" },
    { id: "135", value: "Palau" },
    { id: "136", value: "Panama" },
    { id: "137", value: "Papua New Guinea" },
    { id: "138", value: "Paraguay" },
    { id: "139", value: "Peru" },
    { id: "140", value: "Philippines" },
    { id: "141", value: "Poland" },
    { id: "142", value: "Portugal" },
    { id: "143", value: "Qatar" },
    { id: "144", value: "Romania" },
    { id: "145", value: "Russia" },
    { id: "146", value: "Rwanda" },
    { id: "147", value: "Saint Kitts and Nevis" },
    { id: "148", value: "Saint Lucia" },
    { id: "149", value: "Saint Vincent and the Grenadines" },
    { id: "150", value: "Samoa" },
    { id: "151", value: "San Marino" },
    { id: "152", value: "Sao Tome and Principe" },
    { id: "153", value: "Saudi Arabia" },
    { id: "154", value: "Senegal" },
    { id: "155", value: "Serbia" },
    { id: "156", value: "Seychelles" },
    { id: "157", value: "Sierra Leone" },
    { id: "158", value: "Singapore" },
    { id: "159", value: "Slovakia" },
    { id: "160", value: "Slovenia" },
    { id: "161", value: "Solomon Islands" },
    { id: "162", value: "Somalia" },
    { id: "163", value: "South Africa" },
    { id: "164", value: "South Sudan" },
    { id: "165", value: "Spain" },
    { id: "166", value: "Sri Lanka" },
    { id: "167", value: "Sudan" },
    { id: "168", value: "Suriname" },
    { id: "169", value: "Sweden" },
    { id: "170", value: "Switzerland" },
    { id: "171", value: "Syria" },
    { id: "172", value: "Taiwan" },
    { id: "173", value: "Tajikistan" },
    { id: "174", value: "Tanzania" },
    { id: "175", value: "Thailand" },
    { id: "176", value: "Togo" },
    { id: "177", value: "Tonga" },
    { id: "178", value: "Trinidad and Tobago" },
    { id: "179", value: "Tunisia" },
    { id: "180", value: "Turkey" },
    { id: "181", value: "Turkmenistan" },
    { id: "182", value: "Tuvalu" },
    { id: "183", value: "Uganda" },
    { id: "184", value: "Ukraine" },
    { id: "185", value: "United Arab Emirates" },
    { id: "186", value: "United Kingdom" },
    { id: "187", value: "United States" },
    { id: "188", value: "Uruguay" },
    { id: "189", value: "Uzbekistan" },
    { id: "190", value: "Vanuatu" },
    { id: "191", value: "Vatican City" },
    { id: "192", value: "Venezuela" },
    { id: "193", value: "Vietnam" },
    { id: "194", value: "Yemen" },
    { id: "195", value: "Zambia" },
    { id: "196", value: "Zimbabwe" }
];